Mox.defmock(IngressMock, for: Ingress)
Mox.defmock(Ingress.Services.LambdaMock, for: Ingress.Behaviours.Service)
Mox.defmock(Ingress.Services.HTTPMock, for: Ingress.Behaviours.Service)
Mox.defmock(Ingress.Services.HTTPClientMock, for: Ingress.HTTPClient)
ExUnit.start(trace: true)
