Mox.defmock(BelfrageMock, for: Belfrage)
Mox.defmock(Belfrage.Clients.HTTPMock, for: Belfrage.Clients.HTTP)
Mox.defmock(Belfrage.Clients.LambdaMock, for: Belfrage.Clients.Lambda)
Mox.defmock(Belfrage.Clients.HTTP.MachineGunMock, for: Belfrage.Clients.HTTP.MachineGun)
Mox.defmock(Belfrage.AWS.STSMock, for: Belfrage.AWS.STS)
