defmodule Routes.Specs.SportVideos do
  def specs do
    %{
      owner: "sfv-team@bbc.co.uk",
      runbook: "https://confluence.dev.bbc.co.uk/display/SFV/Short+Form+Video+Run+Book",
      platform: Webcore
    }
  end

    def sports_disciplines_routes do
  [
    "africa",
    "american-football",
    "archery",
    "athletics",
    "badminton",
    "baseball",
    "basketball",
    "bodypositive",
    "bowls",
    "boxing",
    "canoeing",
    "commonwealth-games",
    "cricket",
    "cycling",
    "darts",
    "disability-sport",
    "diving",
    "england",
    "equestrian",
    "fencing",
    "football",
    "formula1",
    "formula-one",
    "gaelic-games",
    "get-inspired",
    "golf",
    "gymnastics",
    "handball",
    "hockey",
    "horse-racing",
    "ice-hockey",
    "judo",
    "mixed-martial-arts",
    "modern-pentathlon",
    "motogp",
    "motorsport",
    "netball",
    "northern-ireland",
    "olympics",
    "rowing",
    "rugby-league",
    "rugby-union",
    "sailing",
    "scotland",
    "shooting",
    "snooker",
    "speedway",
    "sports-personality",
    "squash",
    "swimming",
    "table-tennis",
    "taekwondo",
    "tennis",
    "triathlon",
    "volleyball",
    "wales",
    "water-polo",
    "weightlifting",
    "winter-olympics",
    "winter-sports",
    "wrestling"
  ]
end
  
end
