name: Check labels
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  fail-for-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled DO NOT MERGE
        env:
          PR_LABEL_NAMES: ${{ github.event.pull_request.labels.*.name }}
        if: contains(${{ env.PR_LABEL_NAMES }}, 'DO NOT MERGE')
        run: |
          echo "This PR is currently labeled to not be merged."
          exit 1