name: Check Labels
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  fail-for-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Fail if PR labeled 'DO NOT MERGE'
        if: contains(github.event.pull_request.labels.*.name, 'DO NOT MERGE')
        run: |
          echo "The label for this PR indicates that it should not be merged."
          exit 1
      - name: Fail if PR labeled 'invalid'
        if: contains(github.event.pull_request.labels.*.name, 'invalid')
        run: |
          echo "The label for this PR indicates that it is invalid."
          exit 1