name: Check labels
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  fail-for-labels:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        label: ['DO NOT MERGE', 'invalid']
    steps:
      - name: Fail if PR label indicates it should not be merged
        timeout-minutes: 1
        if: contains(github.event.pull_request.labels.*.name, ${{ matrix.label }})
        run: |
          echo "The label for this PR indicates that it should not be merged."
          exit 1