name: Check labels
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  fail-for-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled DO NOT MERGE
        if: |
          labels=('DO NOT MERGE' 'invalid')
          pr_label=github.event.pull_request.labels.*.name
          echo $pr_label

          for label in "${LABELS[@]}"; do
              contains($pr_label, *"$label"* ]];
          done
        run: |
          echo "This PR is currently labeled to indicate it should not be merged."
          exit 1