name: Check labels
on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  fail-for-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled DO NOT MERGE
        if: contains(github.event.pull_request.labels.*.name, 'DO NOT MERGE')
        run: |
          echo "This PR is currently labeled to indicate it should not be merged."
          exit 1